### ISSUE TITLE
404 on client login

### ISSUE THREAD

**Issue by brightkan** [nickovs/unificontrol#29]
I get a 404 error when I try to login the.
 self.client.login()
unificontrol.exceptions.UnifiTransportError: 404:

**Comment by menvol3** [comment]
Hi @brightkan ,

Could you please explain what you did to solve it ?

I’m receiving
`Max retries exceeded with url: /api/s/default/stat/guest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1125)')))` with cert=none

**Comment by brightkan** [comment]
Share the code.  I try to reproduce the error
